import { VDRDataRoom, VDRFolder, VDRDocument, VDRLink, VDRViewerEvent, VDRQnAItem, VDRAuditLog } from "../types";

export const INITIAL_DATA_ROOMS: VDRDataRoom[] = [
  {
    id: "vdr-jb-wealth",
    name: "Bank Julius Bär — Wealth Intelligence & Mandate Vault",
    slug: "jb-wealth-vault-2026",
    dealType: "Private Wealth Mandate",
    status: "Active",
    ndaText: `CONFIDENTIALITY & NON-DISCLOSURE AGREEMENT (NDA)\n\nThis Virtual Data Room (VDR) is powered by Papermark on behalf of Bank Julius Bär & Co. Ltd. (Asia Desk). The materials contained herein contain strictly proprietary, commercially sensitive, and confidential financial, regulatory, and credit information.\n\nBy accessing this Data Room, you agree:\n1. To keep all documentation and analytics strictly confidential.\n2. That all documents are subject to dynamic forensic watermarking containing your authenticated email, IP address, and timestamp.\n3. Not to reproduce, forward, screenshot, or distribute any part of these files.\n4. Access may be revoked by the Relationship Manager at any moment.`,
    totalDocuments: 9,
    totalSizeMb: 57.0,
    totalViews: 176,
    avgCompletionPct: 81,
    folders: [
      {
        id: "fld-01",
        indexCode: "01",
        name: "Corporate & Governance Dossier",
        description: "Incorporation certificates, board approvals, and authorized signatory lists",
        restricted: false,
        documentsCount: 2,
      },
      {
        id: "fld-02",
        indexCode: "02",
        name: "Financials & Portfolio Valuations",
        description: "Audited balance sheets, Q2 2026 performance attribution, and DCF stress models",
        restricted: false,
        documentsCount: 1,
      },
      {
        id: "fld-03",
        indexCode: "03",
        name: "Lombard Credit & Facility Deeds",
        description: "Master credit agreements, collateral haircut schedules, and margin call thresholds",
        restricted: true,
        documentsCount: 2,
      },
      {
        id: "fld-04",
        indexCode: "04",
        name: "Mandate Guidelines & SAA Policy",
        description: "Strategic asset allocation limits, rebalancing triggers, and risk profile constraints",
        restricted: false,
        documentsCount: 1,
      },
      {
        id: "fld-05",
        indexCode: "05",
        name: "Compliance, AML & ESG Due Diligence",
        description: "Source of wealth verification, tax residency certificates, and ESG exclusion lists",
        restricted: false,
        documentsCount: 2,
      },
      {
        id: "fld-06",
        indexCode: "06",
        name: "Private Market Co-Investments",
        description: "Venture debt term sheets, PE subscription booklets, and capital call calendars",
        restricted: true,
        documentsCount: 1,
      },
    ],
    documents: [
      {
        id: "doc-01",
        folderId: "fld-03",
        title: "Julius Bär Lombard Facility Agreement & Margin Schedule (2026)",
        fileName: "JB_Lombard_Credit_Facility_Agreement_2026.pdf",
        fileType: "pdf",
        fileSizeBytes: 4200000,
        pageCount: 5,
        uploadedAt: "2026-08-15",
        uploadedBy: "Priscilla Ong (Senior RM)",
        version: 2,
        watermarkEnabled: true,
        downloadAllowed: false,
        status: "Active",
        docCategory: "Lombard",
        expiresAt: "2027-08-15",
        summary: "Binding terms governing USD 10.0M multicurrency revolving Lombard facility with collateral advance rates and 80.0% margin call trigger.",
        pages: [
          {
            pageNumber: 1,
            title: "Facility Overview & Credit Commitment",
            content: "BANK JULIUS BÄR & CO. LTD.\nMulticurrency Revolving Lombard Credit Deed\n\nCredit Limit: USD 10,000,000\nApplicable Benchmark: SOFR + 115 bps\nMargin Call LTV: 80.0%\nLiquidation LTV: 85.0%\nEligible Collateral: Sovereign Bonds, High-Yield Debt, Megacap Equities subject to JB Haircut Schedule.",
            avgTimeSpentSeconds: 45,
          },
          {
            pageNumber: 2,
            title: "Collateral Haircuts & Concentration Rules",
            content: "SCHEDULE A: ADVANCE RATES\n- Tier 1 Equities (US/EU Large Cap): 60% Advance Rate\n- Tier 2 Equities (Mid Cap / Regional): 40% Advance Rate\n- Tier 1 Sovereign Debt: 90% Advance Rate\n- Single Stock Cap: No single position may exceed 20% of eligible collateral base without approval.",
            avgTimeSpentSeconds: 95,
          },
          {
            pageNumber: 3,
            title: "Margin Call & Liquidation Mechanics",
            content: "OPERATIONAL MARGIN PROTOCOLS\nIf portfolio LTV breaches 80.0% at close of business:\n1. 24-hour formal notice issued to Client and RM.\n2. Client must deposit cash, pledge supplementary eligible assets, or execute collateral sale within 48 hours.\n3. If LTV touches 85.0%, Bank reserves right to liquidate unhedged positions immediately.",
            avgTimeSpentSeconds: 160,
          },
          {
            pageNumber: 4,
            title: "Covenants & Negative Pledges",
            content: "RESTRICTIVE COVENANTS\n- Borrower shall maintain primary tax residency in Singapore/HK.\n- No secondary cross-collateralization with third-party lenders without written consent.\n- Periodic disclosure of global liabilities across offshore jurisdictions.",
            avgTimeSpentSeconds: 70,
          },
          {
            pageNumber: 5,
            title: "Execution & Signatures",
            content: "IN WITNESS WHEREOF, the parties hereto have caused this Agreement to be duly executed.\n\nFor Bank Julius Bär & Co. Ltd:\n[Authorized Signature] Priscilla Ong, Executive Director\n[Credit Committee Approval: Ref CC-2026-0881]\n\nFor Borrower:\n[Authorized Signature] Dr. Arthur Chen, Managing Partner",
            avgTimeSpentSeconds: 30,
          },
        ],
        viewCount: 48,
        uniqueViewers: 14,
      },
      {
        id: "doc-02",
        folderId: "fld-04",
        title: "Strategic Asset Allocation Mandate & 2026 Geopolitical Playbook",
        fileName: "JB_Advisory_SAA_Mandate_2026.pdf",
        fileType: "pdf",
        fileSizeBytes: 6500000,
        pageCount: 4,
        uploadedAt: "2026-08-20",
        uploadedBy: "Julius Bär Chief Investment Office",
        version: 3,
        watermarkEnabled: true,
        downloadAllowed: true,
        status: "Active",
        docCategory: "Mandate",
        expiresAt: "2027-12-31",
        summary: "Investment guidelines detailing 2026 asset class weights, tactical energy hedges following Hormuz conflict, and duration targets.",
        pages: [
          {
            pageNumber: 1,
            title: "Macro Regime: The 2026 Geopolitical Transition",
            content: "CIO INVESTMENT OUTLOOK 2026\nKey drivers:\n1. Middle East naval blockade lifting and oil price stabilisation ($75-$85/bbl).\n2. Central bank rate pivot: Fed easing 50bps, ECB stabilizing terminal rates.\n3. Tactical shift: Harvest gains from commodity overweights, re-anchor into high-grade fixed income.",
            avgTimeSpentSeconds: 52,
          },
          {
            pageNumber: 2,
            title: "Strategic Bands: Balanced Growth Mandate",
            content: "TARGET ALLOCATION BANDS (BALGRO)\n- Equities: Target 50% (Min 40%, Max 60%)\n- Fixed Income: Target 30% (Min 20%, Max 45%)\n- Commodities / Gold: Target 8% (Min 2%, Max 15%)\n- Cash & Money Market: Target 7% (Min 2%, Max 15%)\n- Alternatives & Structured Notes: Target 5% (Max 12%)",
            avgTimeSpentSeconds: 110,
          },
          {
            pageNumber: 3,
            title: "Single Position & Sector Caps",
            content: "CONCENTRATION LIMITS\n- Max single equity position: 10% of total portfolio market value.\n- Sector hard cap: Max 25% exposure in any single GICS sector (excluding sovereign debt).\n- Derivative leverage: Net delta exposure strictly bounded within 110% of total equity.",
            avgTimeSpentSeconds: 88,
          },
          {
            pageNumber: 4,
            title: "Rebalancing Protocol",
            content: "AUTOMATED REBALANCING RULES\nRebalancing triggers automatically when any asset class drifts by >= 5.0% from target band for 10 consecutive trading sessions. The RM will generate pre-cleared rebalancing trade tickets.",
            avgTimeSpentSeconds: 40,
          },
        ],
        viewCount: 62,
        uniqueViewers: 22,
      },
      {
        id: "doc-03",
        folderId: "fld-02",
        title: "Q2 2026 Multi-Asset Portfolio Performance Attribution",
        fileName: "JB_Q2_2026_Attribution_Report.xlsx",
        fileType: "xlsx",
        fileSizeBytes: 3100000,
        pageCount: 3,
        uploadedAt: "2026-08-01",
        uploadedBy: "Portfolio Analytics Desk",
        version: 1,
        watermarkEnabled: true,
        downloadAllowed: true,
        status: "Active",
        docCategory: "Corporate",
        expiresAt: "2026-12-31",
        summary: "Granular breakdown of YTD performance: +4.2% driven by energy equities and gold hedges offsetting tech valuation pullback.",
        pages: [
          {
            pageNumber: 1,
            title: "Executive P&L Summary",
            content: "YEAR-TO-DATE PORTFOLIO PERFORMANCE\nBeginning AUM (Dec 31, 2025): USD 14,200,000\nCurrent AUM (Aug 26, 2026): USD 14,800,000\nNet Unrealised Gain: +USD 600,000 (+4.22%)\nSharpe Ratio: 1.42 | Maximum Drawdown: -3.8% (June Tech correction)",
            avgTimeSpentSeconds: 40,
          },
          {
            pageNumber: 2,
            title: "Asset Class Contribution Matrix",
            content: "ATTRIBUTION BY ASSET CLASS:\n1. Commodities & Energy: +2.85% contribution (Hormuz oil spike)\n2. Fixed Income & Credit: +1.40% contribution (Yield lock-in)\n3. Global Equities: -0.25% contribution (US tech pullback vs APAC rally)\n4. Currency Impact: +0.22% (USD strength vs EUR/JPY)",
            avgTimeSpentSeconds: 78,
          },
          {
            pageNumber: 3,
            title: "Top 5 Winners and Detractors",
            content: "TOP CONTRIBUTORS:\n- SPDR S&P Oil & Gas (+28.4% return)\n- Physical Gold Trust (+18.2% return)\n- US Treasury 4.25% 2034 (+4.8% return)\n\nTOP DETRACTORS:\n- NVIDIA Corp (-14.2% YTD)\n- ASML Holding NV (-11.8% YTD)",
            avgTimeSpentSeconds: 65,
          },
        ],
        viewCount: 35,
        uniqueViewers: 11,
      },
      {
        id: "doc-04",
        folderId: "fld-05",
        title: "Julius Bär ESG Exclusions & Binding Defense Screening Dossier",
        fileName: "JB_Sustainability_Policy_Exclusions_2026.pdf",
        fileType: "pdf",
        fileSizeBytes: 2800000,
        pageCount: 3,
        uploadedAt: "2026-07-28",
        uploadedBy: "Head of Responsible Wealth",
        version: 1,
        watermarkEnabled: true,
        downloadAllowed: false,
        status: "Active",
        docCategory: "Mandate",
        expiresAt: "2027-07-28",
        summary: "Binding exclusion list under Julius Bär Responsible Wealth mandate, including controversial defense contractors and fossil thermal coal thresholds.",
        pages: [
          {
            pageNumber: 1,
            title: "Scope of Sustainable Mandates",
            content: "JULIUS BÄR SUSTAINABILITY POLICY FRAMEWORK\nApplies to all clients holding Sustainable Balanced (SUSBAL) and ESG Growth mandates. Mandates require strict adherence to international conventions (UN Global Compact, Ottawa Convention on cluster munitions).",
            avgTimeSpentSeconds: 35,
          },
          {
            pageNumber: 2,
            title: "Prohibited Sectors & Exclusions",
            content: "CATEGORY A: ZERO TOLERANCE (AUTOMATIC EXCLUSION)\n- Cluster munitions, anti-personnel mines, nuclear weapons manufacturers.\n- Tobacco producers (>5% revenue).\n- Thermal coal mining (>10% revenue).\n\nNOTE: RTX Corp and defense manufacturers fall under mandatory screening.",
            avgTimeSpentSeconds: 120,
          },
          {
            pageNumber: 3,
            title: "Remediation & Divestment Timelines",
            content: "DIVESTMENT TIMELINE\nUpon detection of an excluded security in a Sustainable Mandate portfolio:\n- RM notified within 24 hours.\n- Remediation trade executed within 5 business days to avoid regulatory censure.",
            avgTimeSpentSeconds: 50,
          },
        ],
        viewCount: 22,
        uniqueViewers: 8,
      },
      {
        id: "doc-05",
        folderId: "fld-06",
        title: "Project Meridian — Series B Co-Investment Term Sheet & Cap Table",
        fileName: "Meridian_Series_B_TermSheet_Confidential.pdf",
        fileType: "pdf",
        fileSizeBytes: 5100000,
        pageCount: 4,
        uploadedAt: "2026-08-18",
        uploadedBy: "Private Markets Syndicate",
        version: 1,
        watermarkEnabled: true,
        downloadAllowed: false,
        status: "Expiring Soon",
        docCategory: "Syndicate",
        expiresAt: "2026-09-15",
        summary: "USD 25.0M Series B expansion round for enterprise cyber-defense AI. Co-investment allocation pre-cleared for Julius Bär UHNW clients. Subscription booklet & KYC verification expire 15 September 2026.",
        pages: [
          {
            pageNumber: 1,
            title: "Investment Opportunity Summary",
            content: "PROJECT MERIDIAN — PRIVATE CO-INVESTMENT\nTarget: Meridian AI Defense Systems Ltd.\nRound Size: USD 25,000,000\nPre-Money Valuation: USD 115,000,000\nLead Investor: Benchmark Global Technology Partners\nJulius Bär Syndicate Allocation: USD 5,000,000 (Min ticket: USD 500k)",
            avgTimeSpentSeconds: 65,
          },
          {
            pageNumber: 2,
            title: "Financial Metrics & ARR Growth",
            content: "FINANCIAL HIGHLIGHTS (USD)\n- 2024 ARR: $8.2M\n- 2025 ARR: $22.4M (173% YoY)\n- 2026 Run-rate ARR: $41.0M\n- Gross Margins: 84%\n- Net Dollar Retention: 138%",
            avgTimeSpentSeconds: 140,
          },
          {
            pageNumber: 3,
            title: "Governance & Liquidity Rights",
            content: "KEY TERMS\n- 1x Non-participating Liquidation Preference.\n- Information rights: Quarterly financials + annual audited reports.\n- Expected Exit: US NASDAQ IPO (estimated Q4 2028).",
            avgTimeSpentSeconds: 90,
          },
          {
            pageNumber: 4,
            title: "Subscription Procedure",
            content: "HOW TO PARTICIPATE\nComplete Subscription Booklet and KYC verification before 15 September 2026. Capital call drawdowns expected in two 50% tranches.",
            avgTimeSpentSeconds: 45,
          },
        ],
        viewCount: 19,
        uniqueViewers: 6,
      },
      {
        id: "doc-06",
        folderId: "fld-01",
        title: "Certificate of Incorporation & Beneficial Ownership Register",
        fileName: "Chen_Holdings_Pte_Ltd_Incorp_Cert.pdf",
        fileType: "pdf",
        fileSizeBytes: 1800000,
        pageCount: 2,
        uploadedAt: "2026-01-10",
        uploadedBy: "Client Onboarding Team",
        version: 1,
        watermarkEnabled: true,
        downloadAllowed: false,
        status: "Active",
        docCategory: "Corporate",
        expiresAt: "2028-03-14",
        summary: "ACRA certified true copy of Chen Family Holdings Pte. Ltd. registration and 100% UBO verification.",
        pages: [
          {
            pageNumber: 1,
            title: "ACRA Certificate of Incorporation",
            content: "ACCOUNTING AND CORPORATE REGULATORY AUTHORITY (SINGAPORE)\nUEN: 202109842K\nCompany: CHEN WEALTH HOLDINGS PTE. LTD.\nIncorporated: 14 March 2021\nPrincipal Activities: Family Office & Investment Holding.",
            avgTimeSpentSeconds: 25,
          },
          {
            pageNumber: 2,
            title: "Register of Registrable Controllers",
            content: "BENEFICIAL OWNERSHIP (UBO)\nUltimate Beneficial Owner: Dr. Arthur Chen (100% Ordinary Voting Shares).\nSingapore Tax Identification: S7823901E\nRegistered Office: Marina Bay Financial Centre Tower 2, Singapore.",
            avgTimeSpentSeconds: 30,
          },
        ],
        viewCount: 14,
        uniqueViewers: 5,
      },
      {
        id: "doc-07",
        folderId: "fld-01",
        title: "Bilateral Non-Disclosure Agreement (NDA) — Arthur Chen Family Office",
        fileName: "JB_Mutual_NDA_Chen_Family_Office_Executed.pdf",
        fileType: "pdf",
        fileSizeBytes: 2100000,
        pageCount: 3,
        uploadedAt: "2025-09-12",
        uploadedBy: "Legal & Compliance Desk",
        version: 1,
        watermarkEnabled: true,
        downloadAllowed: true,
        status: "Expiring Soon",
        docCategory: "NDA",
        expiresAt: "2026-09-12",
        summary: "Annual executed bilateral NDA covering proprietary family office financial disclosures, Lombard credit margin terms, and co-investment syndicate allocations. Mandatory annual renewal required within 30 days.",
        pages: [
          {
            pageNumber: 1,
            title: "Confidentiality Undertaking & Scope",
            content: "MUTUAL CONFIDENTIALITY AND NON-DISCLOSURE AGREEMENT\nEffective Date: 12 September 2025\nParties: Bank Julius Bär & Co. Ltd. and Chen Wealth Holdings Pte. Ltd. (Dr. Arthur Chen).\n\nTerm: Valid for exactly 12 calendar months expiring 12 September 2026.\nGoverning Law: Republic of Singapore (SIAC Arbitration).\nScope: All proprietary investment strategies, credit terms, and syndicated private placements.",
            avgTimeSpentSeconds: 60,
          },
          {
            pageNumber: 2,
            title: "Authorized Representatives & Permitted Disclosures",
            content: "PERMITTED REPRESENTATIVES\nDisclosure permitted strictly to primary RM (Priscilla Ong), designated wealth planner, external tax counsel (Baker McKenzie), and family office investment director.\n\nBreach Covenants: Unauthorised disclosure gives rise to injunctive relief and statutory liquidated damages under Singapore law.",
            avgTimeSpentSeconds: 45,
          },
          {
            pageNumber: 3,
            title: "Renewal & Termination Protocols",
            content: "ANNUAL EXPIRATION & RE-EXECUTION\nThis Agreement terminates automatically on 12 September 2026 unless renewed in writing by both authorized signatories.\n\nNotice of Expiration: Bank compliance systems will issue notice 30 days prior to expiry. Failure to renew triggers automated restriction of virtual data room access.",
            avgTimeSpentSeconds: 40,
          },
        ],
        viewCount: 38,
        uniqueViewers: 9,
      },
      {
        id: "doc-08",
        folderId: "fld-05",
        title: "Annual KYC & AML Due Diligence Profile — Dr. Arthur Chen",
        fileName: "KYC_AML_Risk_Profile_Recertification_2026.pdf",
        fileType: "pdf",
        fileSizeBytes: 3400000,
        pageCount: 4,
        uploadedAt: "2025-09-18",
        uploadedBy: "Financial Crime Compliance",
        version: 2,
        watermarkEnabled: true,
        downloadAllowed: false,
        status: "Expiring Soon",
        docCategory: "KYC",
        expiresAt: "2026-09-18",
        summary: "Mandatory MAS & HKMA annual UHNW client source-of-wealth verification and PEP risk profile recertification dossier. Annual recertification deadline within 30 days.",
        pages: [
          {
            pageNumber: 1,
            title: "Client Identification & PEP Screening",
            content: "CLIENT DUE DILIGENCE (CDD) SUMMARY\nClient Name: Dr. Arthur Chen (Born 1968, Singapore)\nID: S7823901E | PEP Status: Clean (No Politically Exposed Person links)\nAdverse Media: Screened through World-Check One (Zero negative hits)\nRisk Classification: Low-to-Medium (Standard CDD Enhanced Monitoring).",
            avgTimeSpentSeconds: 50,
          },
          {
            pageNumber: 2,
            title: "Source of Wealth (SoW) Corroboration",
            content: "SOURCE OF WEALTH (SoW) ANALYSIS\nPrimary Wealth Origin: Founder & Managing Partner of Chen Biomedical Technologies (divested 2019 for USD 180M).\nSecondary Origin: Singapore commercial real estate portfolio and high-dividend equities.\nVerified Net Worth: USD 84.5M (Liquid AUM at Julius Bär: USD 14.8M).",
            avgTimeSpentSeconds: 85,
          },
          {
            pageNumber: 3,
            title: "Tax Residency & CRS / FATCA Validation",
            content: "TAX RESIDENCY & JURISDICTION COMPLIANCE\nPrimary Tax Domicile: Singapore (Inland Revenue Authority of Singapore IRAS).\nCRS Self-Certification: Signed and valid.\nFATCA Status: Non-US Person (W-8BEN-E on file).\nRecertification Cycle: Annual (Expires 18 September 2026).",
            avgTimeSpentSeconds: 65,
          },
          {
            pageNumber: 4,
            title: "Annual Compliance Sign-Off & Expiration",
            content: "MAS NOTICE 626 ANNUAL RECERTIFICATION\nLast Verified: 18 September 2025\nNext Expiration: 18 September 2026 (Annual 365-day renewal requirement)\nAction Required: RM Priscilla Ong must execute updated client declaration and bank statement re-verification before expiration date.",
            avgTimeSpentSeconds: 35,
          },
        ],
        viewCount: 29,
        uniqueViewers: 7,
      },
      {
        id: "doc-09",
        folderId: "fld-03",
        title: "Lombard Collateral Valuation Certificate — Prime SG Commercial Asset",
        fileName: "Collateral_Valuation_Cert_Q3_2026.pdf",
        fileType: "pdf",
        fileSizeBytes: 2900000,
        pageCount: 3,
        uploadedAt: "2026-03-01",
        uploadedBy: "Credit Risk & Collateral Desk",
        version: 1,
        watermarkEnabled: true,
        downloadAllowed: false,
        status: "Expiring Soon",
        docCategory: "Lombard",
        expiresAt: "2026-09-01",
        summary: "Independent Knight Frank appraisal certificate for secondary collateral pledged against Lombard credit line. Semi-annual valuation validity expires in 6 days (01 September 2026).",
        pages: [
          {
            pageNumber: 1,
            title: "Appraisal Certificate & Pledged Property",
            content: "INDEPENDENT COLLATERAL VALUATION CERTIFICATE\nValuer: Knight Frank Singapore\nSubject Property: 12 Marina Boulevard, Level 34 Commercial Strata Unit\nPledged In Favor Of: Bank Julius Bär & Co. Ltd.\nAppraised Market Value: SGD 18,500,000 (USD 14,000,000 equivalent).",
            avgTimeSpentSeconds: 40,
          },
          {
            pageNumber: 2,
            title: "Lombard Haircut & Loan Headroom",
            content: "CREDIT COMMITTEE ADVANCE DETERMINATION\nApproved Haircut: 40% (60% Advance Rate = USD 8,400,000 credit capacity)\nExisting Lombard Drawdown: USD 4,200,000\nCollateral Coverage Ratio: 2.0x\nValuation Certificate Expiry: 01 September 2026 (Mandatory 6-month refresh).",
            avgTimeSpentSeconds: 70,
          },
          {
            pageNumber: 3,
            title: "Covenants on Valuation Expiration",
            content: "COLLATERAL VALUATION RE-APPRAISAL REQUIREMENT\nUnder Credit Deed Clause 8.4, collateral appraisal must be refreshed semi-annually.\nIf renewed appraisal is not uploaded by 01 September 2026, advance rate will be stepped down from 60% to 40%, creating immediate margin warning.",
            avgTimeSpentSeconds: 55,
          },
        ],
        viewCount: 24,
        uniqueViewers: 8,
      },
    ],
    links: [
      {
        id: "lnk-01",
        slug: "jb-chen-diligence-2026",
        name: "Arthur Chen Family Office — Due Diligence Access",
        url: "https://papermark.io/d/jb-chen-diligence-2026",
        createdAt: "2026-08-20",
        expiresAt: "2026-09-30",
        requireEmail: true,
        requireNda: true,
        watermarkEnabled: true,
        allowDownload: false,
        passwordProtected: true,
        password: "JB2026Chen!",
        viewsCount: 74,
        lastViewedAt: "2026-09-04 18:24",
        active: true,
      },
      {
        id: "lnk-02",
        slug: "jb-meridian-syndicate",
        name: "Project Meridian — Series B Investor Syndicate",
        url: "https://papermark.io/d/jb-meridian-syndicate",
        createdAt: "2026-08-22",
        expiresAt: "2026-09-15",
        requireEmail: true,
        requireNda: true,
        watermarkEnabled: true,
        allowDownload: false,
        passwordProtected: false,
        viewsCount: 42,
        lastViewedAt: "2026-09-04 14:10",
        active: true,
        targetFolderId: "fld-06",
      },
      {
        id: "lnk-03",
        slug: "jb-lombard-audit",
        name: "Lombard Facility Credit Committee Review",
        url: "https://papermark.io/d/jb-lombard-audit",
        createdAt: "2026-08-24",
        expiresAt: "2026-10-01",
        requireEmail: true,
        requireNda: false,
        watermarkEnabled: true,
        allowDownload: true,
        passwordProtected: false,
        viewsCount: 26,
        lastViewedAt: "2026-09-03 09:45",
        active: true,
        targetFolderId: "fld-03",
      },
    ],
    viewers: [
      {
        id: "view-01",
        viewerEmail: "arthur.chen@chenfamily.sg",
        viewerIp: "203.116.12.84",
        viewerLocation: "Singapore (Central)",
        viewerDevice: "macOS • Chrome 128",
        linkId: "lnk-01",
        documentId: "doc-01",
        documentTitle: "Julius Bär Lombard Facility Agreement & Margin Schedule (2026)",
        timestamp: "2026-09-04 18:24",
        durationSeconds: 410,
        completionPct: 100,
        pagesViewed: [1, 2, 3, 4, 5],
        watermarkSignature: "arthur.chen@chenfamily.sg • 203.116.12.84 • 2026-09-04 18:24",
        downloaded: false,
        ndaSigned: true,
      },
      {
        id: "view-02",
        viewerEmail: "cfo@chenfamily.sg",
        viewerIp: "203.116.12.85",
        viewerLocation: "Singapore (Central)",
        viewerDevice: "Windows 11 • Edge 127",
        linkId: "lnk-01",
        documentId: "doc-01",
        documentTitle: "Julius Bär Lombard Facility Agreement & Margin Schedule (2026)",
        timestamp: "2026-09-04 16:50",
        durationSeconds: 320,
        completionPct: 80,
        pagesViewed: [1, 2, 3],
        watermarkSignature: "cfo@chenfamily.sg • 203.116.12.85 • 2026-09-04 16:50",
        downloaded: false,
        ndaSigned: true,
      },
      {
        id: "view-03",
        viewerEmail: "investment@meridianpartners.hk",
        viewerIp: "119.237.40.12",
        viewerLocation: "Hong Kong (Central)",
        viewerDevice: "iPadOS 18 • Safari",
        linkId: "lnk-02",
        documentId: "doc-05",
        documentTitle: "Project Meridian — Series B Co-Investment Term Sheet & Cap Table",
        timestamp: "2026-09-04 14:10",
        durationSeconds: 340,
        completionPct: 100,
        pagesViewed: [1, 2, 3, 4],
        watermarkSignature: "investment@meridianpartners.hk • 119.237.40.12 • 2026-09-04 14:10",
        downloaded: false,
        ndaSigned: true,
      },
      {
        id: "view-04",
        viewerEmail: "alanlimkw@gmail.com",
        viewerIp: "192.168.1.104",
        viewerLocation: "Singapore",
        viewerDevice: "macOS • Chrome 128",
        linkId: "lnk-01",
        documentId: "doc-02",
        documentTitle: "Strategic Asset Allocation Mandate & 2026 Geopolitical Playbook",
        timestamp: "2026-09-04 11:15",
        durationSeconds: 290,
        completionPct: 100,
        pagesViewed: [1, 2, 3, 4],
        watermarkSignature: "alanlimkw@gmail.com • 192.168.1.104 • 2026-09-04 11:15",
        downloaded: false,
        ndaSigned: true,
      },
    ],
    qnaItems: [
      {
        id: "qna-01",
        documentId: "doc-01",
        documentTitle: "Julius Bär Lombard Facility Agreement & Margin Schedule (2026)",
        askedByEmail: "cfo@chenfamily.sg",
        askedAt: "2026-09-04 17:02",
        question: "Can we substitute the sovereign bonds in Sub-account B with high-grade SGD statutory board bonds without resetting the 80% margin trigger?",
        status: "Answered",
        answeredBy: "Priscilla Ong (Senior RM)",
        answeredAt: "2026-09-04 17:45",
        answer: "Yes. Singapore Statutory Board bonds (AAA rated) enjoy an 85% advance rate under Schedule A, maintaining equivalent collateral headroom with zero impact on the 80% margin call threshold.",
      },
      {
        id: "qna-02",
        documentId: "doc-05",
        documentTitle: "Project Meridian — Series B Co-Investment Term Sheet & Cap Table",
        askedByEmail: "investment@meridianpartners.hk",
        askedAt: "2026-09-04 14:35",
        question: "Is the Series B syndicate round open to non-Singapore domiciled family trusts?",
        status: "In Review",
      },
    ],
    auditLogs: [
      {
        id: "log-01",
        timestamp: "2026-09-04 18:24:10",
        userOrEmail: "arthur.chen@chenfamily.sg",
        action: "VIEW_PAGE",
        details: "Viewed Page 3 ('Margin Call & Liquidation Mechanics') of Lombard Facility Agreement",
        ipAddress: "203.116.12.84",
        riskRating: "Low",
      },
      {
        id: "log-02",
        timestamp: "2026-09-04 18:22:04",
        userOrEmail: "arthur.chen@chenfamily.sg",
        action: "SIGN_NDA",
        details: "Executed digital NDA agreement for link 'jb-chen-diligence-2026'",
        ipAddress: "203.116.12.84",
        riskRating: "Low",
      },
      {
        id: "log-03",
        timestamp: "2026-09-04 17:45:22",
        userOrEmail: "priscilla.ong@juliusbaer.com",
        action: "ASK_QNA",
        details: "Published official response to Q&A #qna-01 from cfo@chenfamily.sg",
        ipAddress: "10.45.2.19",
        riskRating: "Low",
      },
      {
        id: "log-04",
        timestamp: "2026-09-04 11:15:00",
        userOrEmail: "alanlimkw@gmail.com",
        action: "VIEW_PAGE",
        details: "Opened Strategic Asset Allocation Mandate with dynamic watermark overlay",
        ipAddress: "192.168.1.104",
        riskRating: "Low",
      },
      {
        id: "log-05",
        timestamp: "2026-08-22 09:00:00",
        userOrEmail: "priscilla.ong@juliusbaer.com",
        action: "CREATE_LINK",
        details: "Generated secure Papermark link 'jb-meridian-syndicate' with watermark & NDA mandatory",
        ipAddress: "10.45.2.19",
        riskRating: "Low",
      },
    ],
  },
];

// Helper functions for VDR actions
export function getVDRDataRooms(): VDRDataRoom[] {
  return INITIAL_DATA_ROOMS;
}

export function createVDRShareLink(
  dataRoomId: string,
  linkData: Omit<VDRLink, "id" | "url" | "createdAt" | "viewsCount" | "lastViewedAt" | "active">
): VDRLink {
  const room = INITIAL_DATA_ROOMS.find((r) => r.id === dataRoomId) || INITIAL_DATA_ROOMS[0];
  const newLink: VDRLink = {
    ...linkData,
    id: `lnk-${Date.now()}`,
    url: `https://papermark.io/d/${linkData.slug}`,
    createdAt: new Date().toISOString().split("T")[0],
    viewsCount: 0,
    lastViewedAt: null,
    active: true,
  };
  room.links.unshift(newLink);
  return newLink;
}

export function uploadVDRDocument(
  dataRoomId: string,
  docData: Omit<VDRDocument, "id" | "uploadedAt" | "version" | "viewCount" | "uniqueViewers">
): VDRDocument {
  const room = INITIAL_DATA_ROOMS.find((r) => r.id === dataRoomId) || INITIAL_DATA_ROOMS[0];
  const newDoc: VDRDocument = {
    ...docData,
    id: `doc-${Date.now()}`,
    uploadedAt: new Date().toISOString().split("T")[0],
    version: 1,
    viewCount: 0,
    uniqueViewers: 0,
  };
  room.documents.unshift(newDoc);
  room.totalDocuments += 1;
  room.totalSizeMb += parseFloat((newDoc.fileSizeBytes / 1e6).toFixed(1));
  const folder = room.folders.find((f) => f.id === docData.folderId);
  if (folder) {
    folder.documentsCount += 1;
  }
  return newDoc;
}

// Expiration calculation & badge helper functions
export function getDaysUntilExpiration(expiresAt?: string, referenceDateStr: string = "2026-09-04"): number | null {
  if (!expiresAt) return null;
  const refDate = new Date(referenceDateStr).getTime();
  const expDate = new Date(expiresAt).getTime();
  const diffTime = expDate - refDate;
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
}

export function isDocumentExpiringSoon(doc: VDRDocument, referenceDateStr: string = "2026-09-04", thresholdDays: number = 30): boolean {
  if (!doc.expiresAt) return false;
  const days = getDaysUntilExpiration(doc.expiresAt, referenceDateStr);
  return days !== null && days <= thresholdDays;
}

export function getExpiringVDRDocuments(
  referenceDateStr: string = "2026-09-04",
  thresholdDays: number = 30
): { doc: VDRDocument; room: VDRDataRoom; daysRemaining: number }[] {
  const results: { doc: VDRDocument; room: VDRDataRoom; daysRemaining: number }[] = [];
  for (const room of INITIAL_DATA_ROOMS) {
    for (const doc of room.documents) {
      if (doc.expiresAt) {
        const days = getDaysUntilExpiration(doc.expiresAt, referenceDateStr);
        if (days !== null && days <= thresholdDays) {
          results.push({ doc, room, daysRemaining: days });
        }
      }
    }
  }
  return results.sort((a, b) => a.daysRemaining - b.daysRemaining);
}
